# Generated by Django 5.1.7 on 2025-04-27 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myapp_db',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topics', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=500)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
            ],
        ),
    ]
